name: Build

on:
  push:
    branches:
    - master
    tags:
    - v*.*.*
  pull_request:
    branches:
    - master

env:
  RUSTFLAGS: --deny warnings

jobs:
  all:
    name: All

    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - uses: Swatinem/rust-cache@v2

    - name: Test
      run: cargo test --all

    - name: Clippy
      run: cargo clippy --all --all-targets

    - name: Check Formatting
      run: cargo fmt --all -- --check
